// Set Up Next.js Dashboard App
// Source: https://nextjs.org/learn/dashboard-app/getting-started
// Generated by BuildBridge

console.log("Starting: Set Up Next.js Dashboard App");

// Step 1: Open terminal and change directory
